export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_PRODUCT_BY_BARCODE = 'GET_PRODUCT_BY_BARCODE'

export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAIL = "POST_PRODUCT_FAIL"

export const GET_ONEPRODUCT_SUCCESS = "GET_ONEPRODUCT_SUCCESS"
export const GET_ONEPRODUCT_FAIL = "GET_ONEPRODUCT_FAIL"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"


export const DELETE_PRODUCT = "DELETE_PRODUCT"

export const SEARCH_PRODUCT = "SEARCH_PRODUCT"
export const FILTER_PRODUCT_CATEGORY = "FILTER_PRODUCT_CATEGORY"


export const GET_CLIENTS_LOAD = "GET_CLIENTS_LOAD"
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS"
export const GET_CLIENTS_FAIL = "GET_CLIENTS_FAIL"

export const POST_CLIENT_SUCCESS = "POST_CLIENT_SUCCESS "
export const POST_CLIENT_FAIL = "POST_CLIENT_FAIL "

export const GET_ONECLIENT = "GET_ONECLIENT"

export const UPDATE_CLIENT = "UPDATE_CLIENT"

export const DELETE_CLIENT = "DELETE_CLIENT"

export const SEARCH_CLIENT = "SEARCH_CLIENT"

export const ADD_PRODUCTS_ORDER = "ADD_PRODUCTS_ORDER"
export const ADD_CLIENT_ORDER = "ADD_CLIENT_ORDER"
export const INITIALE_PRODUCTS = "INITIALE_PRODUCTS"
export const SAVE_ORDER = "SAVE_ORDER"

export const GET_ORDERS_LOAD = "GET_ORDERS_LOAD";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
export const GET_ORDERS_BY_MONTH = "GET_ORDERS_BY_MONTH"

export const GENERATE_INVOICE = "GENERATE_INVOICE"
export const SEND_MAIL_ORDER = 'SEND_MAIL_ORDER'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER = 'USER_REGISTER'
export const GET_AUTH_USER = 'GET_AUTH_USER'
export const LOAD_USER = 'LOAD_USER'
export const AUTH_ERRORS = 'AUTH_ERRORS'
